name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false 
          submodules: true

      - name: Build
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Reinstall Node.js dependencies
        run: |
          cd Project_alpha
          rm -rf node_modules # Remove existing node_modules
          npm ci # Reinstall dependencies for the current platform

      - name: Cache .NET packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/*.fsproj') }}
          restore-keys: ${{ runner.os }}-dotnet-
        
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: Project_alpha/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('Project_alpha/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install dependencies
        run: dotnet tool restore

      - name: Build project
        run: dotnet publish -c Release -o out

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out